services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../data/qdrant:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true

  discord-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    command: python -m src.discord-bot.bot
    profiles:
      - discord
